export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_TAGS = "FETCH_TAGS";
export const FETCH_TAGGED_ARTICLES = "FETCH_TAGGED_ARTICLES";
export const SET_SELECT_TAGS = "SET_SELECT_TAGS";
